deployments:
 default:
 dockerimage: ubuntu:latest
 build_steps:
 - apt-get update && apt-get install -y python python-pip virtualenv libssl-dev
libpq-dev git build-essential libfontconfig1 libfontconfig1-dev
 - apt-get install -y locales
 - sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen &&
locale-gen
 - export LC_ALL=en_US.UTF-8
 - export LANG=en_US.UTF-8
 - export LANGUAGE=en_US.UTF-8
 - pip install setuptools pip --upgrade --force-reinstall
 - pip install djangocms-installer
 - mkdir myproject
 - cd myproject
 - djangocms -f -s -p . mysite
 - sed -i -e 's/ALLOWED_HOSTS.*/ALLOWED_HOSTS = ["0.0.0.0"]/' /myproject/mysite/settings.py
 - python manage.py migrate
 launch_steps: python manage.py runserver 0.0.0.0:80
